---
description: This notebook guides you through the process of using Ready Signal to add external control
  data, such as census and weather data, to improve time series predictions.
file_name: DataRobot_Ready_Signal.ipynb
languages:
  - python
authors:
  - Baylen Springer
  - Matt Schaefer
  - Chen Wang
authors_email:
  - baylen.springer@readysignal.com
  - matt.schaefer@readysignal.com
  - chen.wang@datarobot.com
smoke_test:
  run_smoke_test: false
maintainers:
  - João Gomes
maintainers_email:
  - joao@datarobot.com
tags: []
title: Predict lumber prices with Ready Signal and time series forecasts
