---
title: Observability Starter for Anthropic Claude model
file_name: anthropic_claude_observability_starter.ipynb
description: |-
  This accelerator shows how you can easily enable observability in your Anthropic AI based Generative AI Solutions with DataRobot's LLMOps feature tools.
languages:
  - python
maintainers:
  - Abdul Jilani
maintainers_email:
  - abdul.jilani@datarobot.com
tags: []
smoke_test:
  run_smoke_test: false
