---
title: Observability starter for Azure OpenAI models
file_name: gpt_observability_starter.ipynb
description: |-
  This accelerator aims to show how to easily enable observability in your Azure OpenAI-based Generative AI Solutions with LLMOps feature tools from DataRobot. 
languages:
  - python
maintainers:
  - Abdul Jilani
maintainers_email:
  - abdul.jilani@datarobot.com
tags: []
smoke_test:
  run_smoke_test: false
