title: Zero-shot text classification for error analysis
file_name: Zero Shot Test Classification for Error Analysis.ipynb
description: |-
  This notebook outlines how to use zero-shot text classification with large language models (LLMs), focusing on its application in error analysis of supervised text classification models.
languages:
  - python
maintainers:
  - Glen Koundry
maintainers_email:
  - glen.koundry@datarobot.com
tags: []
