title: Build daily trading volume profiles
file_name: VolumeProfile_starter_code.ipynb
description: |-
  This notebook provides a template for using DataRobot time series models to build a daily trading volume profile.
languages:
  - python
maintainers:
  - João Gomes
maintainers_email:
  - joao.gomes@datarobot.com
tags: []
